[[main]]
  identifier = "home"
  name = "Home"
  url = "/en/"
  weight = 1

[[main]]
  identifier = "post"
  name = "Posts"
  url = "/en/posts"
  weight = 2

[[main]]
  identifier = "slides"
  name = "Slides"
  url = "/en/slides"
  weight = 3

[[main]]
  identifier = "about"
  name = "About"
  url = "/en/about"
  weight = 4

[[main]]
  identifier = "tags"
  name = "Tags"
  url = "/en/tags"
  weight = 5

[[social]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/hlc23"
  weight = 1
